apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.repository }}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        command: ["bash", "/entrypoint.sh"]  # Run the entrypoint script for password validation
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: tcp
    port: {{ .Values.redisService.port }}
    targetPort: {{ .Values.redisService.targetPort }}
  selector:
    app: redis